minute = """The Federal Reserve Board eagle logo links to home page
Minutes of the Federal Open Market Committee
March 20, 2001
A meeting of the Federal Open Market Committee was held in the offices of the Board of Governors of the Federal Reserve System in Washington, D.C., beginning at 9:00 a.m. on Tuesday, March 20, 2001.

Present:
Mr. Greenspan, Chairman
Mr. McDonough, Vice Chairman
Mr. Ferguson
Mr. Gramlich
Mr. Hoenig
Mr. Kelley
Mr. Meyer
Ms. Minehan
Mr. Moskow
Mr. Poole
Messrs. Jordan, McTeer, Santomero, Stern, and Stewart, Alternate Members of the Federal Open Market Committee

Messrs. Broaddus, Guynn, and Parry, Presidents of the Federal Reserve Banks of Richmond, Atlanta, and San Francisco respectively

Mr. Kohn, Secretary and Economist
Mr. Bernard, Deputy Secretary
Mr. Gillum, Assistant Secretary
Ms. Fox, Assistant Secretary
Mr. Baxter, Deputy General Counsel
Ms. Johnson, Economist
Mr. Stockton, Economist
Ms. Cumming, Messrs. Fuhrer, Hakkio, Howard, Hunter, Lindsey, Rasche, Reinhart, Slifman, and Wilcox, Associate Economists

Mr. Kos, Manager, System Open Market Account

Ms. Smith and Mr. Winn, Assistants to the Board, Office of Board Members, Board of Governors

Mr. Ettin, Deputy Director, Division of Research and Statistics, Board of Governors

Mr. Simpson, Senior Adviser, Division of Research and Statistics, Board of Governors

Messrs. Madigan, Oliner, and Struckmeyer, Associate Directors, Divisions of Monetary Affairs, Research and Statistics, and Research and Statistics, Board of Governors

Mr. Whitesell, Assistant Director, Division of Monetary Affairs, Board of Governors

Ms. Low, Open Market Secretariat Assistant, Division of Monetary Affairs, Board of Governors

Mr. Barron, First Vice President, Federal Reserve Bank of Atlanta

Messrs. Eisenbeis and Goodfriend, Mses. Krieger and Mester, and Mr. Rolnick, Senior Vice Presidents, Federal Reserve Banks of Atlanta, Richmond, New York, Philadelphia, and Minneapolis respectively

Ms. Orrenius, Economist, Federal Reserve Bank of Dallas

Mr. Trehan, Research Advisor, Federal Reserve Bank of San Francisco

Mr. Haubrich, Consultant, Federal Reserve Bank of Cleveland

By unanimous vote, the minutes of the meeting of the Federal Open Market Committee held on January 30-31, 2001, were approved.

By unanimous vote, David Wilcox was elected to serve as an Associate Economist for the period until the first regularly scheduled meeting of the Committee after December 31, 2001.

The Manager of the System Open Market Account reported on developments in foreign exchange markets. There had been no operations in foreign currencies for the System's account since the previous meeting.

The Manager also reported on developments in domestic financial markets and on System open market transactions in U.S. government securities and federal agency obligations during the period January 31, 2001, through March 19, 2001. By unanimous vote, the Committee ratified these transactions.

The Committee then turned to a discussion of the economic and financial outlook and the implementation of monetary policy over the intermeeting period ahead. A summary of the economic and financial information available at the time of the meeting and of the Committee's discussion is provided below, followed by the domestic policy directive that was approved by the Committee and issued to the Federal Reserve Bank of New York.

The information reviewed at this meeting suggested that economic activity continued to expand very slowly in the first quarter. Growth of final spending apparently picked up slightly, with consumer expenditures recording another moderate gain, business purchases of equipment and software increasing sluggishly after a fourth-quarter decline, and homebuilding remaining relatively firm. However, inventory overhangs were still apparent in some industries, and manufacturing production was cut sharply further. Overall employment gains were relatively well maintained, and labor markets were still tight though showing signs of softening. Price inflation had picked up a little but, abstracting from energy, had remained relatively subdued.

After a sluggish fourth quarter, private nonfarm payroll employment rose at a slightly higher rate on average in January and February, though still considerably below the pace of the first three quarters of 2000. Manufacturing and related industries, notably help-supply and wholesale trade, experienced further large declines in payrolls in the January-February period. However, hiring elsewhere held up relatively well, especially in construction, which recorded a surge in employment in January. While the labor market remained tight on balance, the unemployment rate increased to 4.2 percent in February, and other indicators such as initial claims for unemployment insurance suggested that pressures in labor markets had begun to abate.

The contraction in industrial production that began in October accelerated and broadened in the first two months of the year. In manufacturing, output fell further in the motor vehicle sector, and production continued to decelerate in high-tech industries. The rate of capacity utilization in manufacturing dropped noticeably in January and February to a level further below its long-run average.

Against a background of slowing income gains and a sizable pullback in consumer sentiment since last autumn, consumer spending evidently grew only moderately on balance in January and February. Purchases of motor vehicles picked up in response to increased marketing incentives put in place by Chrysler and General Motors, and retail sales of items other than motor vehicles climbed moderately. Spending on services was held down in January (latest data) by reduced expenditures for heating services as winter temperatures returned to more seasonal levels following unusually cold weather late last year; excluding heating, however, spending on other services rose slowly.

The decline in mortgage rates that began around the middle of last year continued to provide support to residential building activity. Total housing starts rose somewhat further in January and February, reflecting net increases in both single-family and, especially, multifamily units. Sales of new homes dropped sharply in January (latest data), after having surged in December, but remained quite robust by historical standards. Sales of existing homes rebounded in January after having fallen considerably in December and were up slightly on balance over the two months.

The limited available information suggested that business fixed investment was firming early this year after a decline in the fourth quarter of last year. Nominal shipments of nondefense capital goods other than aircraft and parts changed little on balance in December and January, while prices of high-tech equipment continued to fall. Moreover, orders for nondefense capital goods turned up briskly in January after a sharp fourth-quarter drop. Nonresidential construction activity continued its robust rise early in the year. Strength in building activity was widespread across the sector, most notably in new office construction.

Business inventories on a book-value basis increased in January at about the rapid fourth-quarter pace; inventory positions appeared to be especially large for construction materials, metals, electrical equipment, paper, chemicals, and textiles. In the manufacturing sector, overall stocks jumped in January while shipments fell, and the aggregate inventory-shipments ratio rose to its highest level in two years. In the wholesale trade sector, aggregate stocks fell again in January and the sector's inventory-sales ratio edged down to the middle of its very narrow range for the past year. Retail stocks continued to climb in January, but sales rose by more; the sector's inventory-sales ratio also edged lower, but it remained near the top of its range for the past twelve months.

The U.S. trade deficit in goods and services changed little in December but posted a new record high for the fourth quarter. The value of exports dropped substantially in that quarter, with notable declines occurring in agricultural products, aircraft, automotive products, computers and semiconductors, consumer goods, and telecommunications equipment. The value of imports remained at the high level recorded in the third quarter. Lower imports of automotive products, chemicals, computers and semiconductors, and steel were offset by higher imports of consumer goods and telecommunications equipment and smaller increases in other categories of trade. Economic growth in the foreign industrial countries was at a moderate rate on average in the fourth quarter. Expansion in the euro area picked up, while growth in Canada and the United Kingdom slowed significantly. The Japanese economy rebounded in the fourth quarter but was little changed on balance over the second half of the year, and recent indicators suggested a sharply weaker performance in the early part of this year. In addition, growth in the major developing countries slowed markedly in the fourth quarter, with the slowdown in most of those countries reflecting weaker demand for their exports.

Price inflation had picked up a bit recently. The consumer price index (CPI) jumped in January (latest data), reflecting a surge in energy prices; moreover, the index increased considerably more during the twelve months ending in January than it did during the previous twelve months. The core component of the CPI also accelerated in January and on a year-over-year basis, but by lesser amounts than did the total index. The increase in the core personal consumption expenditure (PCE) chain-type price index in January matched that of the core CPI; on a year-over-year basis, however, the pickup in core PCE inflation was a little smaller than that for the core CPI. At the producer level, core finished goods retraced in February only part of the sizable step-up in prices recorded in January, and core producer price inflation was up somewhat on a year-over-year basis. With regard to labor costs, recent data also pointed to some acceleration. Compensation per hour in the nonfarm business sector advanced appreciably more rapidly in the fourth quarter of 2000 and for the year as a whole. That trend also showed through to the average hourly earnings of production or nonsupervisory workers through February, which exhibited a roughly similar acceleration.

At its meeting on January 30-31, 2001, the Committee adopted a directive that called for maintaining conditions in reserve markets consistent with a decrease of 50 basis points in the intended level of the federal funds rate, to about 5-1/2 percent. This move, in conjunction with the easing on January 3, was intended to help guard against cumulative weakness in economic activity and to provide some support to a rebound in growth later in the year. In the existing circumstances, the members agreed that the balance of risks remained weighted toward conditions that could generate economic weakness in the foreseeable future. Though rapid advances in underlying productivity were expected to continue, the adjustments to stocks of capital, consumer goods, and inventories to more sustainable levels were only partly completed, and financial markets remained unsettled.

Open market operations were directed throughout the intermeeting period toward maintaining the federal funds rate at the Committee's reduced target level of 5-1/2 percent, and the funds rate stayed close to that target. However, incoming economic data, a steady flow of disappointing corporate earnings reports, related sharp declines in stock prices, and a notable drop in consumer confidence led market participants to conclude that more monetary easing would be required. Yields on Treasury securities, both short- and long-term, moved appreciably lower. However, rates on high-yield private debt obligations fell only a little, and banks further tightened standards and terms on business loans, given the weakening outlook for profits. Broad indexes of U.S. stock market prices moved sharply lower, with the tech-heavy Nasdaq experiencing an especially large drop. Nonetheless, the trade-weighted value of the dollar rose somewhat over the intermeeting interval in terms of many of the major foreign currencies. The dollar strengthened most against the currencies of countries that were seen to have the greatest potential for economic weakening, notably Japan. The dollar also posted a small gain against an index of the currencies of other important trading partners.

The broad monetary aggregates continued to grow rapidly in February, though at slightly lower rates than in January. The strength in M2 was concentrated in its liquid components, apparently in response to the further narrowing of opportunity costs, the yield advantage of money funds relative to longer-term investments, and the appeal of a safe haven from volatile equity markets. M3 grew somewhat less rapidly than M2; a pullback in the issuance of bank-managed liabilities, particularly large time deposits, was associated with slower expansion of bank credit. Growth of domestic nonfinancial debt decelerated noticeably in January (latest data), reflecting reduced expansion of debt in the nonfederal sectors coupled with a larger contraction in the amount of federal debt outstanding.

The staff forecast prepared for this meeting suggested that, after a period of slow growth associated in part with an inventory correction, the economic expansion would gradually regain strength over the next two years and move toward a rate near the staff's current estimate of the growth of the economy's potential output. The period of sub-par expansion was expected to foster an appreciable easing of pressures on resources and some moderation in core price inflation. The forecast anticipated that the expansion of domestic final demand would be held back to an extent by the decline in household net worth associated with the downturn that had occurred in equity prices, the lingering effects of last year's relatively high interest rates, and the continuation of relatively stringent terms and conditions on some types of loans by financial institutions. As a result, growth of spending on consumer durables was expected to be appreciably below the rapid pace in the first half of last year, and housing demand would increase only a little from its recent level. Business fixed investment, notably outlays for equipment and software, was projected to resume relatively robust growth after a period of adjustment of capital stocks to more desirable levels; growth abroad was seen as supporting the expansion of U.S. exports; and fiscal policy was assumed to become more expansionary.

In the Committee's discussion of current and prospective economic developments, members commented that the recent statistical and anecdotal information had been mixed, but they viewed evolving business conditions as consistent on the whole with a continued softness in economic activity. Members noted that consumer spending had strengthened early in the year and housing activity had remained at a relatively high level. These positive developments needed to be weighed against an appreciable weakening in business investment spending and the near-term restraining effects of a drawdown in inventories. Looking ahead, while sales and production data suggested that excess inventories were being worked off, the adjustment did not appear to have been completed. Beyond the inventory correction, the members continued to anticipate an acceleration of the expansion over time, though likely on a more delayed basis and at a more gradual pace than they had forecast earlier. They noted a number of favorable underlying factors that would tend to support a rebound, including solid productivity growth, stable low inflation, generally sound financial institutions, lower interest rates, and relatively robust expansion in many measures of money. However, the members saw clear downside risks in the outlook for consumer and investment spending in the context of the marked decline that had occurred in equity prices and consumer confidence, and in expected business profitability, and they were concerned that weaker exports might also hold down the expansion of economic activity. With regard to the outlook for inflation, some recent measures of increases in core prices had fluctuated on the high side of earlier expectations, but apart from energy prices and medical costs, inflation was still relatively quiescent. With the growth in output likely to remain below the expansion of the economy's potential for a while, members anticipated that inflation would remain subdued.

Mirroring the statistics for the nation as a whole, business conditions in different parts of the country displayed mixed industry patterns, but members reported that overall business activity currently appeared to be growing at a sluggish pace in most regions, and business contacts were exhibiting a heightened sense of caution, or even concern, in some industries. In their review of developments in key sectors of the economy, members indicated that they saw favorable prospects for continued moderate growth in consumer expenditures, though considerable uncertainty surrounded this outlook. Downside risks cited by the members included the substantial declines that had already occurred in measures of consumer confidence and equity wealth, and the possibility that consumer sentiment might be undermined even further by continued volatility and additional declines in the stock market and by rising concerns about job losses amid persistent announcements of layoffs. Members also referred to the retarding effects on consumer expenditures of elevated levels of household debt and high energy costs. Against this background, consumers might well endeavor to boost their savings, and even a fairly small increase in what currently was a quite low saving rate would have large damping effects on aggregate demand that could weaken, if not abort, the expansion. To date, however, overall consumer spending had remained relatively strong and seemingly at odds with measures of consumer confidence and reduced equity wealth. How this divergence might eventually be resolved was a significant source of uncertainty and downside risk. On balance, while there were reasons to be concerned about the outlook for consumer spending, members believed that recent spending trends and the outlook for further growth in employment and incomes pointed to continued expansion in this key sector of the economy, though likely at a relatively sluggish pace.

Another major source of downside risk to the expansion was business fixed investment. Spending for equipment and software declined in the fourth quarter, and the available statistical and anecdotal reports pointed to weakness during the first half of this year, largely reflecting developments in high-tech industries. Substantial downward adjustments to expected near-term business earnings had persisted, suggesting that firms saw investment as much less profitable than they had before and that cash flows would be constrained. Many businesses also were inhibited in their investment activities by less accommodative financial conditions associated with weaker equity markets and tighter credit terms and conditions imposed by banking institutions. As a consequence, a substantial volume of planned investment was being postponed, if not cancelled. The capital stock had grown at an unsustainable pace for a time, so some downshifting in investment was inevitable. Moreover, those earlier very substantial investment outlays seemed to have created excess capacity in a number of industries, and how large an adjustment in spending for business equipment might now be underway was still unclear, especially with regard to high-tech industries. At the same time, the information available for the first quarter indicated considerable strength in nonresidential construction activity, including large outlays on public sector infrastructure projects in some areas. On balance, business spending for plant and equipment was likely to pick up only gradually this year. Over the longer term, however, a return to more robust business investment seemed likely, and indeed business earnings forecasts beyond the nearer term had not declined very much, reflecting continuing expectations of substantial profit opportunities related to persisting strong gains in productivity.

Housing activity was generally holding up well across the country as the effects of appreciably reduced mortgage interest rates apparently compensated for the negative effects of declining financial wealth on the demand for housing. While housing construction was generally described as elevated, some members referred to overbuilding or weakness in some local housing markets. It was noted that homebuilders were generally optimistic about the prospects for the year ahead, given their current backlogs and expectations of further growth in employment and incomes.

The ongoing adjustments in business inventories had played a significant role in curbing the growth of economic activity in recent months, but such adjustments seemed likely gradually to become a more neutral factor over the balance of this year. In the motor vehicle industry, inventory liquidation had been especially pronounced and the process now seemed largely completed. However, the inventory-correction process in high-tech industries apparently was not as far along. In the absence of renewed weakness in overall final demand, which could not be ruled out given current consumer and business confidence, production would need to pick up at some point to accommodate ongoing final demand. Some members observed that the adjustment in inventories might require more time than they had anticipated earlier. In any event, completion of the process clearly would foster an upturn in manufacturing activity.

Members commented on the downside risks to U.S. exports and the U.S. expansion from what appeared to be softening economic conditions in a number of important foreign economies. In some countries, the risks were exacerbated by the apparent inability or unwillingness of government officials to address underlying structural problems in their economies and financial systems. Members noted anecdotal reports of weakening business conditions in a number of Asian and South American nations. The potential impact on exports of less vigor in the global economy would be augmented, of course, by the strength of the dollar in foreign exchange markets.

Although labor markets in general remained tight throughout the nation, anecdotal reports of less scarce labor resources were becoming more frequent in some areas or occupations. Some price increases had been noted; however, apart from the energy and health care sectors, price inflation had remained relatively subdued, evidently reflecting the combination of diminished growth in overall demand and strong competitive pressures in most markets. With regard to the outlook for wages and prices, members commented that the prospects for an extended period of growth in demand at a pace below the economy's potential should ease pressures on labor and other resources and help to contain inflation.

In the Committee's discussion of policy for the intermeeting period ahead, most of the members preferred and all could support a further easing of reserve conditions consistent with a 50 basis point reduction in the federal funds rate, to 5 percent. The members agreed that a strengthening in the economic expansion over coming quarters was a reasonable expectation, but absent further easing in monetary policy that pickup was unlikely to bring growth to an acceptable pace in the foreseeable future. Business investment would be held back by lower earnings expectations and a capital overhang of unknown dimensions; consumption was subject to downside risks from previous decreases in equity wealth and declining confidence; and the strong dollar and weaker foreign growth would constrain exports. Inflation was likely to be damped by ebbing pressures on labor and product markets. While many of the members generally believed that additional policy easing might well prove to be necessary at some time, the easing favored by most members incorporated what they viewed as an adequate degree of stimulus under current economic conditions and represented an appropriately calibrated step given the uncertainties in the economic outlook. It was noted in this regard that in combination with the two easing actions earlier this year, the Committee would have implemented in a relatively short period a considerable amount of monetary easing whose economic effects would be felt over time. However, some commented that the amount of financial stimulus was much smaller than might otherwise be expected from policy easing of this cumulative amount because it had been accompanied by further declines in stock market prices, more stringent financing terms for many business borrowers, and a stronger dollar, all of which would be holding down domestic spending and production. Indeed, financial markets had come to place some odds on a larger move of 75 basis points in recent days, importantly reflecting the possibility of a presumed policy response to the sizable declines in equity prices that had occurred as earnings prospects proved disappointing. Most members agreed, however, that in the context of their focus on the economy, smaller, possibly more frequent, policy adjustments were appropriate to afford them the opportunity to recalibrate policy in rapidly changing and highly uncertain circumstances.

A few members expressed a preference for a 75 basis point reduction in the federal funds rate. In their view, a more forceful action was justified by current and prospective economic conditions.

The members agreed that even with a further 50 basis point reduction in the federal funds rate, the risks to the economy would remain decidedly to the downside. This conclusion would be reflected in the press statement to be released after today's meeting. The statement also would emphasize the need for close monitoring of rapidly evolving economic conditions. The members anticipated that in the relatively long interval before the next regularly scheduled meeting on May 15, 2001, economic developments might suggest the desirability of a Committee conference call to assess business conditions across the nation and to consider the possible need for a further policy adjustment.

At the conclusion of this discussion, the Committee voted to authorize and direct the Federal Reserve Bank of New York, until it was instructed otherwise, to execute transactions in the System Account in accordance with the following domestic policy directive:

The Federal Open Market Committee seeks monetary and financial conditions that will foster price stability and promote sustainable growth in output. To further its long-run objectives, the Committee in the immediate future seeks conditions in reserve markets consistent with reducing the federal funds rate to an average of around 5 percent.

The vote encompassed approval of the sentence below for inclusion in the press statement to be released shortly after the meeting:

Against the background of its long-run goals of price stability and sustainable economic growth and of the information currently available, the Committee believes that the risks are weighted mainly toward conditions that may generate economic weakness in the foreseeable future.
Votes for this action: Messrs. Greenspan, McDonough, Ferguson, Gramlich, Hoenig, Kelley, Meyer, Ms. Minehan, Messrs. Moskow and Poole.

Votes against this action: None.

The Chairman called for a recess after this vote and convened a meeting of the Board of Governors to consider reductions of one-half percentage point in the discount rate that had been proposed by all the Federal Reserve Banks. After the recess, the Chairman informed the Committee that the pending reductions had been approved.

It was agreed that the next meeting of the Committee would be held on Tuesday, May 15, 2001. The meeting adjourned at 1:15 p.m.

Telephone Conferences
On April 11, 2001, the Committee reviewed economic and financial developments since its last meeting and discussed the possible need for some further easing of monetary policy. The data and anecdotal information were mixed: They did not indicate that the economy had been weakening further, but they raised questions about the potential strength of a rebound in growth over coming quarters. In particular, heightened business concerns about future sales and further downward revisions to expected earnings threatened to restrain capital spending for some time. In the circumstances, the members could see the need for a further easing of policy at some point, though some had a strong preference for taking such actions at regularly scheduled meetings. They all agreed that an easing on this date would not be advisable, inasmuch as the attendant surprise to most outside observers risked unpredictable reactions in financial markets that had been especially volatile in recent days, and additional important data would become available over the near term.

A week later, on April 18, 2001, the Committee held a telephone conference meeting for the purpose of considering a policy easing action. The members noted that the statistical and anecdotal information received since the last conference call had supported their view that an easing of policy would be appropriate. In addition to the continuing concerns about business plans for capital investment, consumer spending had leveled out and confidence had fallen further. In these circumstances, lower interest rates were likely to be necessary to foster more satisfactory economic expansion. With financial markets more settled, and with nearly a month until the Committee's May meeting, an easing move was called for at this time.

Although a few preferred to wait until the next scheduled meeting, all the members supported or could accept a proposal for an easing of reserve conditions consistent with a reduction of 50 basis points in the federal funds rate to a level of 4-1/2 percent. The Committee voted to authorize and direct the Federal Reserve Bank of New York, until it was instructed otherwise, to execute transactions in the System Account in accordance with the following domestic policy directive:


The Federal Open Market Committee seeks monetary and financial conditions that will foster price stability and promote sustainable growth in output. To further its long-run objectives, the Committee in the immediate future seeks conditions in reserve markets consistent with reducing the federal funds rate to an average of around 4-1/2 percent.
The vote encompassed approval of the sentence below for inclusion in the press statement to be released shortly after the meeting:

Against the background of its long-run goals of price stability and sustainable economic growth and of the information currently available, the Committee believes that the risks are weighted mainly toward conditions that may generate economic weakness in the foreseeable future.
Votes for this action: Messrs. Greenspan, McDonough, Ferguson, Gramlich, Hoenig, Kelley, Meyer, Ms. Minehan, Messrs. Moskow and Poole.

Votes against this action: None.

Chairman Greenspan indicated that shortly after this meeting the Board of Governors would consider pending requests of eight Federal Reserve Banks to reduce the discount rate by 50 basis points.

Donald L. Kohn
Secretary
Return to topReturn to top

Home | FOMC
Accessibility
To comment on this site, please fill out our feedback form.
Last update: May 17, 2001, 2:00 PM"""

lmpos = """ABLE
ABUNDANCE
ABUNDANT
ACCLAIMED
ACCOMPLISH
ACCOMPLISHED
ACCOMPLISHES
ACCOMPLISHING
ACCOMPLISHMENT
ACCOMPLISHMENTS
ACHIEVE
ACHIEVED
ACHIEVEMENT
ACHIEVEMENTS
ACHIEVES
ACHIEVING
ADEQUATELY
ADVANCEMENT
ADVANCEMENTS
ADVANCES
ADVANCING
ADVANTAGE
ADVANTAGED
ADVANTAGEOUS
ADVANTAGEOUSLY
ADVANTAGES
ALLIANCE
ALLIANCES
ASSURE
ASSURED
ASSURES
ASSURING
ATTAIN
ATTAINED
ATTAINING
ATTAINMENT
ATTAINMENTS
ATTAINS
ATTRACTIVE
ATTRACTIVENESS
BEAUTIFUL
BEAUTIFULLY
BENEFICIAL
BENEFICIALLY
BENEFIT
BENEFITED
BENEFITING
BENEFITTED
BENEFITTING
BEST
BETTER
BOLSTERED
BOLSTERING
BOLSTERS
BOOM
BOOMING
BOOST
BOOSTED
BREAKTHROUGH
BREAKTHROUGHS
BRILLIANT
CHARITABLE
COLLABORATE
COLLABORATED
COLLABORATES
COLLABORATING
COLLABORATION
COLLABORATIONS
COLLABORATIVE
COLLABORATOR
COLLABORATORS
COMPLIMENT
COMPLIMENTARY
COMPLIMENTED
COMPLIMENTING
COMPLIMENTS
CONCLUSIVE
CONCLUSIVELY
CONDUCIVE
CONFIDENT
CONSTRUCTIVE
CONSTRUCTIVELY
COURTEOUS
CREATIVE
CREATIVELY
CREATIVENESS
CREATIVITY
DELIGHT
DELIGHTED
DELIGHTFUL
DELIGHTFULLY
DELIGHTING
DELIGHTS
DEPENDABILITY
DEPENDABLE
DESIRABLE
DESIRED
DESPITE
DESTINED
DILIGENT
DILIGENTLY
DISTINCTION
DISTINCTIONS
DISTINCTIVE
DISTINCTIVELY
DISTINCTIVENESS
DREAM
EASIER
EASILY
EASY
EFFECTIVE
EFFICIENCIES
EFFICIENCY
EFFICIENT
EFFICIENTLY
EMPOWER
EMPOWERED
EMPOWERING
EMPOWERS
ENABLE
ENABLED
ENABLES
ENABLING
ENCOURAGED
ENCOURAGEMENT
ENCOURAGES
ENCOURAGING
ENHANCE
ENHANCED
ENHANCEMENT
ENHANCEMENTS
ENHANCES
ENHANCING
ENJOY
ENJOYABLE
ENJOYABLY
ENJOYED
ENJOYING
ENJOYMENT
ENJOYS
ENTHUSIASM
ENTHUSIASTIC
ENTHUSIASTICALLY
EXCELLENCE
EXCELLENT
EXCELLING
EXCELS
EXCEPTIONAL
EXCEPTIONALLY
EXCITED
EXCITEMENT
EXCITING
EXCLUSIVE
EXCLUSIVELY
EXCLUSIVENESS
EXCLUSIVES
EXCLUSIVITY
EXEMPLARY
FANTASTIC
FAVORABLE
FAVORABLY
FAVORED
FAVORING
FAVORITE
FAVORITES
FRIENDLY
GAIN
GAINED
GAINING
GAINS
GOOD
GREAT
GREATER
GREATEST
GREATLY
GREATNESS
HAPPIEST
HAPPILY
HAPPINESS
HAPPY
HIGHEST
HONOR
HONORABLE
HONORED
HONORING
HONORS
IDEAL
IMPRESS
IMPRESSED
IMPRESSES
IMPRESSING
IMPRESSIVE
IMPRESSIVELY
IMPROVE
IMPROVED
IMPROVEMENT
IMPROVEMENTS
IMPROVES
IMPROVING
INCREDIBLE
INCREDIBLY
INFLUENTIAL
INFORMATIVE
INGENUITY
INNOVATE
INNOVATED
INNOVATES
INNOVATING
INNOVATION
INNOVATIONS
INNOVATIVE
INNOVATIVENESS
INNOVATOR
INNOVATORS
INSIGHTFUL
INSPIRATION
INSPIRATIONAL
INTEGRITY
INVENT
INVENTED
INVENTING
INVENTION
INVENTIONS
INVENTIVE
INVENTIVENESS
INVENTOR
INVENTORS
LEADERSHIP
LEADING
LOYAL
LUCRATIVE
MERITORIOUS
OPPORTUNITIES
OPPORTUNITY
OPTIMISTIC
OUTPERFORM
OUTPERFORMED
OUTPERFORMING
OUTPERFORMS
PERFECT
PERFECTED
PERFECTLY
PERFECTS
PLEASANT
PLEASANTLY
PLEASED
PLEASURE
PLENTIFUL
POPULAR
POPULARITY
POSITIVE
POSITIVELY
PREEMINENCE
PREEMINENT
PREMIER
PREMIERE
PRESTIGE
PRESTIGIOUS
PROACTIVE
PROACTIVELY
PROFICIENCY
PROFICIENT
PROFICIENTLY
PROFITABILITY
PROFITABLE
PROFITABLY
PROGRESS
PROGRESSED
PROGRESSES
PROGRESSING
PROSPERED
PROSPERING
PROSPERITY
PROSPEROUS
PROSPERS
REBOUND
REBOUNDED
REBOUNDING
RECEPTIVE
REGAIN
REGAINED
REGAINING
RESOLVE
REVOLUTIONIZE
REVOLUTIONIZED
REVOLUTIONIZES
REVOLUTIONIZING
REWARD
REWARDED
REWARDING
REWARDS
SATISFACTION
SATISFACTORILY
SATISFACTORY
SATISFIED
SATISFIES
SATISFY
SATISFYING
SMOOTH
SMOOTHING
SMOOTHLY
SMOOTHS
SOLVES
SOLVING
SPECTACULAR
SPECTACULARLY
STABILITY
STABILIZATION
STABILIZATIONS
STABILIZE
STABILIZED
STABILIZES
STABILIZING
STABLE
STRENGTH
STRENGTHEN
STRENGTHENED
STRENGTHENING
STRENGTHENS
STRENGTHS
STRONG
STRONGER
STRONGEST
SUCCEED
SUCCEEDED
SUCCEEDING
SUCCEEDS
SUCCESS
SUCCESSES
SUCCESSFUL
SUCCESSFULLY
SUPERIOR
SURPASS
SURPASSED
SURPASSES
SURPASSING
TRANSPARENCY
TREMENDOUS
TREMENDOUSLY
UNMATCHED
UNPARALLELED
UNSURPASSED
UPTURN
UPTURNS
VALUABLE
VERSATILE
VERSATILITY
VIBRANCY
VIBRANT
WIN
WINNER
WINNERS
WINNING
WORTHY
"""

lmneg = """ABANDON
ABANDONED
ABANDONING
ABANDONMENT
ABANDONMENTS
ABANDONS
ABDICATED
ABDICATES
ABDICATING
ABDICATION
ABDICATIONS
ABERRANT
ABERRATION
ABERRATIONAL
ABERRATIONS
ABETTING
ABNORMAL
ABNORMALITIES
ABNORMALITY
ABNORMALLY
ABOLISH
ABOLISHED
ABOLISHES
ABOLISHING
ABROGATE
ABROGATED
ABROGATES
ABROGATING
ABROGATION
ABROGATIONS
ABRUPT
ABRUPTLY
ABRUPTNESS
ABSENCE
ABSENCES
ABSENTEEISM
ABUSE
ABUSED
ABUSES
ABUSING
ABUSIVE
ABUSIVELY
ABUSIVENESS
ACCIDENT
ACCIDENTAL
ACCIDENTALLY
ACCIDENTS
ACCUSATION
ACCUSATIONS
ACCUSE
ACCUSED
ACCUSES
ACCUSING
ACQUIESCE
ACQUIESCED
ACQUIESCES
ACQUIESCING
ACQUIT
ACQUITS
ACQUITTAL
ACQUITTALS
ACQUITTED
ACQUITTING
ADULTERATE
ADULTERATED
ADULTERATING
ADULTERATION
ADULTERATIONS
ADVERSARIAL
ADVERSARIES
ADVERSARY
ADVERSE
ADVERSELY
ADVERSITIES
ADVERSITY
AFTERMATH
AFTERMATHS
AGAINST
AGGRAVATE
AGGRAVATED
AGGRAVATES
AGGRAVATING
AGGRAVATION
AGGRAVATIONS
ALERTED
ALERTING
ALIENATE
ALIENATED
ALIENATES
ALIENATING
ALIENATION
ALIENATIONS
ALLEGATION
ALLEGATIONS
ALLEGE
ALLEGED
ALLEGEDLY
ALLEGES
ALLEGING
ANNOY
ANNOYANCE
ANNOYANCES
ANNOYED
ANNOYING
ANNOYS
ANNUL
ANNULLED
ANNULLING
ANNULMENT
ANNULMENTS
ANNULS
ANOMALIES
ANOMALOUS
ANOMALOUSLY
ANOMALY
ANTICOMPETITIVE
ANTITRUST
ARGUE
ARGUED
ARGUING
ARGUMENT
ARGUMENTATIVE
ARGUMENTS
ARREARAGE
ARREARAGES
ARREARS
ARREST
ARRESTED
ARRESTS
ARTIFICIALLY
ASSAULT
ASSAULTED
ASSAULTING
ASSAULTS
ASSERTIONS
ATTRITION
AVERSELY
BACKDATING
BAD
BAIL
BAILOUT
BALK
BALKED
BANKRUPT
BANKRUPTCIES
BANKRUPTCY
BANKRUPTED
BANKRUPTING
BANKRUPTS
BANS
BARRED
BARRIER
BARRIERS
BOTTLENECK
BOTTLENECKS
BOYCOTT
BOYCOTTED
BOYCOTTING
BOYCOTTS
BREACH
BREACHED
BREACHES
BREACHING
BREAK
BREAKAGE
BREAKAGES
BREAKDOWN
BREAKDOWNS
BREAKING
BREAKS
BRIBE
BRIBED
BRIBERIES
BRIBERY
BRIBES
BRIBING
BRIDGE
BROKEN
BURDEN
BURDENED
BURDENING
BURDENS
BURDENSOME
BURNED
CALAMITIES
CALAMITOUS
CALAMITY
CANCEL
CANCELED
CANCELING
CANCELLATION
CANCELLATIONS
CANCELLED
CANCELLING
CANCELS
CARELESS
CARELESSLY
CARELESSNESS
CATASTROPHE
CATASTROPHES
CATASTROPHIC
CATASTROPHICALLY
CAUTION
CAUTIONARY
CAUTIONED
CAUTIONING
CAUTIONS
CEASE
CEASED
CEASES
CEASING
CENSURE
CENSURED
CENSURES
CENSURING
CHALLENGE
CHALLENGED
CHALLENGES
CHALLENGING
CHARGEOFFS
CIRCUMVENT
CIRCUMVENTED
CIRCUMVENTING
CIRCUMVENTION
CIRCUMVENTIONS
CIRCUMVENTS
CLAIMING
CLAIMS
CLAWBACK
CLOSED
CLOSEOUT
CLOSEOUTS
CLOSING
CLOSINGS
CLOSURE
CLOSURES
COERCE
COERCED
COERCES
COERCING
COERCION
COERCIVE
COLLAPSE
COLLAPSED
COLLAPSES
COLLAPSING
COLLISION
COLLISIONS
COLLUDE
COLLUDED
COLLUDES
COLLUDING
COLLUSION
COLLUSIONS
COLLUSIVE
COMPLAIN
COMPLAINED
COMPLAINING
COMPLAINS
COMPLAINT
COMPLAINTS
COMPLICATE
COMPLICATED
COMPLICATES
COMPLICATING
COMPLICATION
COMPLICATIONS
COMPULSION
CONCEALED
CONCEALING
CONCEDE
CONCEDED
CONCEDES
CONCEDING
CONCERN
CONCERNED
CONCERNS
CONCILIATING
CONCILIATION
CONCILIATIONS
CONDEMN
CONDEMNATION
CONDEMNATIONS
CONDEMNED
CONDEMNING
CONDEMNS
CONDONE
CONDONED
CONFESS
CONFESSED
CONFESSES
CONFESSING
CONFESSION
CONFINE
CONFINED
CONFINEMENT
CONFINEMENTS
CONFINES
CONFINING
CONFISCATE
CONFISCATED
CONFISCATES
CONFISCATING
CONFISCATION
CONFISCATIONS
CONFLICT
CONFLICTED
CONFLICTING
CONFLICTS
CONFRONT
CONFRONTATION
CONFRONTATIONAL
CONFRONTATIONS
CONFRONTED
CONFRONTING
CONFRONTS
CONFUSE
CONFUSED
CONFUSES
CONFUSING
CONFUSINGLY
CONFUSION
CONSPIRACIES
CONSPIRACY
CONSPIRATOR
CONSPIRATORIAL
CONSPIRATORS
CONSPIRE
CONSPIRED
CONSPIRES
CONSPIRING
CONTEMPT
CONTEND
CONTENDED
CONTENDING
CONTENDS
CONTENTION
CONTENTIONS
CONTENTIOUS
CONTENTIOUSLY
CONTESTED
CONTESTING
CONTRACTION
CONTRACTIONS
CONTRADICT
CONTRADICTED
CONTRADICTING
CONTRADICTION
CONTRADICTIONS
CONTRADICTORY
CONTRADICTS
CONTRARY
CONTROVERSIAL
CONTROVERSIES
CONTROVERSY
CONVICT
CONVICTED
CONVICTING
CONVICTION
CONVICTIONS
CORRECTED
CORRECTING
CORRECTION
CORRECTIONS
CORRECTS
CORRUPT
CORRUPTED
CORRUPTING
CORRUPTION
CORRUPTIONS
CORRUPTLY
CORRUPTNESS
COSTLY
COUNTERCLAIM
COUNTERCLAIMED
COUNTERCLAIMING
COUNTERCLAIMS
COUNTERFEIT
COUNTERFEITED
COUNTERFEITER
COUNTERFEITERS
COUNTERFEITING
COUNTERFEITS
COUNTERMEASURE
COUNTERMEASURES
CRIME
CRIMES
CRIMINAL
CRIMINALLY
CRIMINALS
CRISES
CRISIS
CRITICAL
CRITICALLY
CRITICISM
CRITICISMS
CRITICIZE
CRITICIZED
CRITICIZES
CRITICIZING
CRUCIAL
CRUCIALLY
CULPABILITY
CULPABLE
CULPABLY
CUMBERSOME
CURTAIL
CURTAILED
CURTAILING
CURTAILMENT
CURTAILMENTS
CURTAILS
CUT
CUTBACK
CUTBACKS
CYBERATTACK
CYBERATTACKS
CYBERBULLYING
CYBERCRIME
CYBERCRIMES
CYBERCRIMINAL
CYBERCRIMINALS
DAMAGE
DAMAGED
DAMAGES
DAMAGING
DAMPEN
DAMPENED
DANGER
DANGEROUS
DANGEROUSLY
DANGERS
DEADLOCK
DEADLOCKED
DEADLOCKING
DEADLOCKS
DEADWEIGHT
DEADWEIGHTS
DEBARMENT
DEBARMENTS
DEBARRED
DECEASED
DECEIT
DECEITFUL
DECEITFULNESS
DECEIVE
DECEIVED
DECEIVES
DECEIVING
DECEPTION
DECEPTIONS
DECEPTIVE
DECEPTIVELY
DECLINE
DECLINED
DECLINES
DECLINING
DEFACE
DEFACED
DEFACEMENT
DEFAMATION
DEFAMATIONS
DEFAMATORY
DEFAME
DEFAMED
DEFAMES
DEFAMING
DEFAULT
DEFAULTED
DEFAULTING
DEFAULTS
DEFEAT
DEFEATED
DEFEATING
DEFEATS
DEFECT
DEFECTIVE
DEFECTS
DEFEND
DEFENDANT
DEFENDANTS
DEFENDED
DEFENDING
DEFENDS
DEFENSIVE
DEFER
DEFICIENCIES
DEFICIENCY
DEFICIENT
DEFICIT
DEFICITS
DEFRAUD
DEFRAUDED
DEFRAUDING
DEFRAUDS
DEFUNCT
DEGRADATION
DEGRADATIONS
DEGRADE
DEGRADED
DEGRADES
DEGRADING
DELAY
DELAYED
DELAYING
DELAYS
DELETERIOUS
DELIBERATE
DELIBERATED
DELIBERATELY
DELINQUENCIES
DELINQUENCY
DELINQUENT
DELINQUENTLY
DELINQUENTS
DELIST
DELISTED
DELISTING
DELISTS
DEMISE
DEMISED
DEMISES
DEMISING
DEMOLISH
DEMOLISHED
DEMOLISHES
DEMOLISHING
DEMOLITION
DEMOLITIONS
DEMOTE
DEMOTED
DEMOTES
DEMOTING
DEMOTION
DEMOTIONS
DENIAL
DENIALS
DENIED
DENIES
DENIGRATE
DENIGRATED
DENIGRATES
DENIGRATING
DENIGRATION
DENY
DENYING
DEPLETE
DEPLETED
DEPLETES
DEPLETING
DEPLETION
DEPLETIONS
DEPRECATION
DEPRESS
DEPRESSED
DEPRESSES
DEPRESSING
DEPRIVATION
DEPRIVE
DEPRIVED
DEPRIVES
DEPRIVING
DERELICT
DERELICTION
DEROGATORY
DESTABILIZATION
DESTABILIZE
DESTABILIZED
DESTABILIZING
DESTROY
DESTROYED
DESTROYING
DESTROYS
DESTRUCTION
DESTRUCTIVE
DETAIN
DETAINED
DETENTION
DETENTIONS
DETER
DETERIORATE
DETERIORATED
DETERIORATES
DETERIORATING
DETERIORATION
DETERIORATIONS
DETERRED
DETERRENCE
DETERRENCES
DETERRENT
DETERRENTS
DETERRING
DETERS
DETRACT
DETRACTED
DETRACTING
DETRIMENT
DETRIMENTAL
DETRIMENTALLY
DETRIMENTS
DEVALUE
DEVALUED
DEVALUES
DEVALUING
DEVASTATE
DEVASTATED
DEVASTATING
DEVASTATION
DEVIATE
DEVIATED
DEVIATES
DEVIATING
DEVIATION
DEVIATIONS
DEVOLVE
DEVOLVED
DEVOLVES
DEVOLVING
DIFFICULT
DIFFICULTIES
DIFFICULTLY
DIFFICULTY
DIMINISH
DIMINISHED
DIMINISHES
DIMINISHING
DIMINUTION
DISADVANTAGE
DISADVANTAGED
DISADVANTAGEOUS
DISADVANTAGES
DISAFFILIATION
DISAGREE
DISAGREEABLE
DISAGREED
DISAGREEING
DISAGREEMENT
DISAGREEMENTS
DISAGREES
DISALLOW
DISALLOWANCE
DISALLOWANCES
DISALLOWED
DISALLOWING
DISALLOWS
DISAPPEAR
DISAPPEARANCE
DISAPPEARANCES
DISAPPEARED
DISAPPEARING
DISAPPEARS
DISAPPOINT
DISAPPOINTED
DISAPPOINTING
DISAPPOINTINGLY
DISAPPOINTMENT
DISAPPOINTMENTS
DISAPPOINTS
DISAPPROVAL
DISAPPROVALS
DISAPPROVE
DISAPPROVED
DISAPPROVES
DISAPPROVING
DISASSOCIATES
DISASSOCIATING
DISASSOCIATION
DISASSOCIATIONS
DISASTER
DISASTERS
DISASTROUS
DISASTROUSLY
DISAVOW
DISAVOWAL
DISAVOWED
DISAVOWING
DISAVOWS
DISCIPLINARY
DISCLAIM
DISCLAIMED
DISCLAIMER
DISCLAIMERS
DISCLAIMING
DISCLAIMS
DISCLOSE
DISCLOSED
DISCLOSES
DISCLOSING
DISCONTINUANCE
DISCONTINUANCES
DISCONTINUATION
DISCONTINUATIONS
DISCONTINUE
DISCONTINUED
DISCONTINUES
DISCONTINUING
DISCOURAGE
DISCOURAGED
DISCOURAGES
DISCOURAGING
DISCREDIT
DISCREDITED
DISCREDITING
DISCREDITS
DISCREPANCIES
DISCREPANCY
DISFAVOR
DISFAVORED
DISFAVORING
DISFAVORS
DISGORGE
DISGORGED
DISGORGEMENT
DISGORGEMENTS
DISGORGES
DISGORGING
DISGRACE
DISGRACEFUL
DISGRACEFULLY
DISHONEST
DISHONESTLY
DISHONESTY
DISHONOR
DISHONORABLE
DISHONORABLY
DISHONORED
DISHONORING
DISHONORS
DISINCENTIVES
DISINTERESTED
DISINTERESTEDLY
DISINTERESTEDNESS
DISLOYAL
DISLOYALLY
DISLOYALTY
DISMAL
DISMALLY
DISMISS
DISMISSAL
DISMISSALS
DISMISSED
DISMISSES
DISMISSING
DISORDERLY
DISPARAGE
DISPARAGED
DISPARAGEMENT
DISPARAGEMENTS
DISPARAGES
DISPARAGING
DISPARAGINGLY
DISPARITIES
DISPARITY
DISPLACE
DISPLACED
DISPLACEMENT
DISPLACEMENTS
DISPLACES
DISPLACING
DISPOSE
DISPOSSESS
DISPOSSESSED
DISPOSSESSES
DISPOSSESSING
DISPROPORTION
DISPROPORTIONAL
DISPROPORTIONATE
DISPROPORTIONATELY
DISPUTE
DISPUTED
DISPUTES
DISPUTING
DISQUALIFICATION
DISQUALIFICATIONS
DISQUALIFIED
DISQUALIFIES
DISQUALIFY
DISQUALIFYING
DISREGARD
DISREGARDED
DISREGARDING
DISREGARDS
DISREPUTABLE
DISREPUTE
DISRUPT
DISRUPTED
DISRUPTING
DISRUPTION
DISRUPTIONS
DISRUPTIVE
DISRUPTS
DISSATISFACTION
DISSATISFIED
DISSENT
DISSENTED
DISSENTER
DISSENTERS
DISSENTING
DISSENTS
DISSIDENT
DISSIDENTS
DISSOLUTION
DISSOLUTIONS
DISTORT
DISTORTED
DISTORTING
DISTORTION
DISTORTIONS
DISTORTS
DISTRACT
DISTRACTED
DISTRACTING
DISTRACTION
DISTRACTIONS
DISTRACTS
DISTRESS
DISTRESSED
DISTURB
DISTURBANCE
DISTURBANCES
DISTURBED
DISTURBING
DISTURBS
DIVERSION
DIVERT
DIVERTED
DIVERTING
DIVERTS
DIVEST
DIVESTED
DIVESTING
DIVESTITURE
DIVESTITURES
DIVESTMENT
DIVESTMENTS
DIVESTS
DIVORCE
DIVORCED
DIVULGE
DIVULGED
DIVULGES
DIVULGING
DOUBT
DOUBTED
DOUBTFUL
DOUBTS
DOWNGRADE
DOWNGRADED
DOWNGRADES
DOWNGRADING
DOWNSIZE
DOWNSIZED
DOWNSIZES
DOWNSIZING
DOWNSIZINGS
DOWNTIME
DOWNTIMES
DOWNTURN
DOWNTURNS
DOWNWARD
DOWNWARDS
DRAG
DRASTIC
DRASTICALLY
DRAWBACK
DRAWBACKS
DROPPED
DROUGHT
DROUGHTS
DURESS
DYSFUNCTION
DYSFUNCTIONAL
DYSFUNCTIONS
EASING
EGREGIOUS
EGREGIOUSLY
EMBARGO
EMBARGOED
EMBARGOES
EMBARGOING
EMBARRASS
EMBARRASSED
EMBARRASSES
EMBARRASSING
EMBARRASSMENT
EMBARRASSMENTS
EMBEZZLE
EMBEZZLED
EMBEZZLEMENT
EMBEZZLEMENTS
EMBEZZLER
EMBEZZLES
EMBEZZLING
ENCROACH
ENCROACHED
ENCROACHES
ENCROACHING
ENCROACHMENT
ENCROACHMENTS
ENCUMBER
ENCUMBERED
ENCUMBERING
ENCUMBERS
ENCUMBRANCE
ENCUMBRANCES
ENDANGER
ENDANGERED
ENDANGERING
ENDANGERMENT
ENDANGERS
ENJOIN
ENJOINED
ENJOINING
ENJOINS
ERODE
ERODED
ERODES
ERODING
EROSION
ERRATIC
ERRATICALLY
ERRED
ERRING
ERRONEOUS
ERRONEOUSLY
ERROR
ERRORS
ERRS
ESCALATE
ESCALATED
ESCALATES
ESCALATING
EVADE
EVADED
EVADES
EVADING
EVASION
EVASIONS
EVASIVE
EVICT
EVICTED
EVICTING
EVICTION
EVICTIONS
EVICTS
EXACERBATE
EXACERBATED
EXACERBATES
EXACERBATING
EXACERBATION
EXACERBATIONS
EXAGGERATE
EXAGGERATED
EXAGGERATES
EXAGGERATING
EXAGGERATION
EXCESSIVE
EXCESSIVELY
EXCULPATE
EXCULPATED
EXCULPATES
EXCULPATING
EXCULPATION
EXCULPATIONS
EXCULPATORY
EXONERATE
EXONERATED
EXONERATES
EXONERATING
EXONERATION
EXONERATIONS
EXPLOIT
EXPLOITATION
EXPLOITATIONS
EXPLOITATIVE
EXPLOITED
EXPLOITING
EXPLOITS
EXPOSE
EXPOSED
EXPOSES
EXPOSING
EXPROPRIATE
EXPROPRIATED
EXPROPRIATES
EXPROPRIATING
EXPROPRIATION
EXPROPRIATIONS
EXPULSION
EXPULSIONS
EXTENUATING
FAIL
FAILED
FAILING
FAILINGS
FAILS
FAILURE
FAILURES
FALLOUT
FALSE
FALSELY
FALSIFICATION
FALSIFICATIONS
FALSIFIED
FALSIFIES
FALSIFY
FALSIFYING
FALSITY
FATALITIES
FATALITY
FATALLY
FAULT
FAULTED
FAULTS
FAULTY
FEAR
FEARS
FELONIES
FELONIOUS
FELONY
FICTITIOUS
FINED
FINES
FIRED
FIRING
FLAW
FLAWED
FLAWS
FORBID
FORBIDDEN
FORBIDDING
FORBIDS
FORCE
FORCED
FORCING
FORECLOSE
FORECLOSED
FORECLOSES
FORECLOSING
FORECLOSURE
FORECLOSURES
FOREGO
FOREGOES
FOREGONE
FORESTALL
FORESTALLED
FORESTALLING
FORESTALLS
FORFEIT
FORFEITED
FORFEITING
FORFEITS
FORFEITURE
FORFEITURES
FORGERS
FORGERY
FRAUD
FRAUDS
FRAUDULENCE
FRAUDULENT
FRAUDULENTLY
FRIVOLOUS
FRIVOLOUSLY
FRUSTRATE
FRUSTRATED
FRUSTRATES
FRUSTRATING
FRUSTRATINGLY
FRUSTRATION
FRUSTRATIONS
FUGITIVE
FUGITIVES
GRATUITOUS
GRATUITOUSLY
GRIEVANCE
GRIEVANCES
GROSSLY
GROUNDLESS
GUILTY
HALT
HALTED
HAMPER
HAMPERED
HAMPERING
HAMPERS
HARASS
HARASSED
HARASSING
HARASSMENT
HARDSHIP
HARDSHIPS
HARM
HARMED
HARMFUL
HARMFULLY
HARMING
HARMS
HARSH
HARSHER
HARSHEST
HARSHLY
HARSHNESS
HAZARD
HAZARDOUS
HAZARDS
HINDER
HINDERED
HINDERING
HINDERS
HINDRANCE
HINDRANCES
HOSTILE
HOSTILITY
HURT
HURTING
IDLE
IDLED
IDLING
IGNORE
IGNORED
IGNORES
IGNORING
ILL
ILLEGAL
ILLEGALITIES
ILLEGALITY
ILLEGALLY
ILLEGIBLE
ILLICIT
ILLICITLY
ILLIQUID
ILLIQUIDITY
IMBALANCE
IMBALANCES
IMMATURE
IMMORAL
IMPAIR
IMPAIRED
IMPAIRING
IMPAIRMENT
IMPAIRMENTS
IMPAIRS
IMPASSE
IMPASSES
IMPEDE
IMPEDED
IMPEDES
IMPEDIMENT
IMPEDIMENTS
IMPEDING
IMPENDING
IMPERATIVE
IMPERFECTION
IMPERFECTIONS
IMPERIL
IMPERMISSIBLE
IMPLICATE
IMPLICATED
IMPLICATES
IMPLICATING
IMPOSSIBILITY
IMPOSSIBLE
IMPOUND
IMPOUNDED
IMPOUNDING
IMPOUNDS
IMPRACTICABLE
IMPRACTICAL
IMPRACTICALITIES
IMPRACTICALITY
IMPRISONMENT
IMPROPER
IMPROPERLY
IMPROPRIETIES
IMPROPRIETY
IMPRUDENT
IMPRUDENTLY
INABILITY
INACCESSIBLE
INACCURACIES
INACCURACY
INACCURATE
INACCURATELY
INACTION
INACTIONS
INACTIVATE
INACTIVATED
INACTIVATES
INACTIVATING
INACTIVATION
INACTIVATIONS
INACTIVITY
INADEQUACIES
INADEQUACY
INADEQUATE
INADEQUATELY
INADVERTENT
INADVERTENTLY
INADVISABILITY
INADVISABLE
INAPPROPRIATE
INAPPROPRIATELY
INATTENTION
INCAPABLE
INCAPACITATED
INCAPACITY
INCARCERATE
INCARCERATED
INCARCERATES
INCARCERATING
INCARCERATION
INCARCERATIONS
INCIDENCE
INCIDENCES
INCIDENT
INCIDENTS
INCOMPATIBILITIES
INCOMPATIBILITY
INCOMPATIBLE
INCOMPETENCE
INCOMPETENCY
INCOMPETENT
INCOMPETENTLY
INCOMPETENTS
INCOMPLETE
INCOMPLETELY
INCOMPLETENESS
INCONCLUSIVE
INCONSISTENCIES
INCONSISTENCY
INCONSISTENT
INCONSISTENTLY
INCONVENIENCE
INCONVENIENCES
INCONVENIENT
INCORRECT
INCORRECTLY
INCORRECTNESS
INDECENCY
INDECENT
INDEFEASIBLE
INDEFEASIBLY
INDICT
INDICTABLE
INDICTED
INDICTING
INDICTMENT
INDICTMENTS
INEFFECTIVE
INEFFECTIVELY
INEFFECTIVENESS
INEFFICIENCIES
INEFFICIENCY
INEFFICIENT
INEFFICIENTLY
INELIGIBILITY
INELIGIBLE
INEQUITABLE
INEQUITABLY
INEQUITIES
INEQUITY
INEVITABLE
INEXPERIENCE
INEXPERIENCED
INFERIOR
INFLICTED
INFRACTION
INFRACTIONS
INFRINGE
INFRINGED
INFRINGEMENT
INFRINGEMENTS
INFRINGES
INFRINGING
INHIBITED
INIMICAL
INJUNCTION
INJUNCTIONS
INJURE
INJURED
INJURES
INJURIES
INJURING
INJURIOUS
INJURY
INORDINATE
INORDINATELY
INQUIRY
INSECURE
INSENSITIVE
INSOLVENCIES
INSOLVENCY
INSOLVENT
INSTABILITY
INSUBORDINATION
INSUFFICIENCY
INSUFFICIENT
INSUFFICIENTLY
INSURRECTION
INSURRECTIONS
INTENTIONAL
INTERFERE
INTERFERED
INTERFERENCE
INTERFERENCES
INTERFERES
INTERFERING
INTERMITTENT
INTERMITTENTLY
INTERRUPT
INTERRUPTED
INTERRUPTING
INTERRUPTION
INTERRUPTIONS
INTERRUPTS
INTIMIDATION
INTRUSION
INVALID
INVALIDATE
INVALIDATED
INVALIDATES
INVALIDATING
INVALIDATION
INVALIDITY
INVESTIGATE
INVESTIGATED
INVESTIGATES
INVESTIGATING
INVESTIGATION
INVESTIGATIONS
INVOLUNTARILY
INVOLUNTARY
IRRECONCILABLE
IRRECONCILABLY
IRRECOVERABLE
IRRECOVERABLY
IRREGULAR
IRREGULARITIES
IRREGULARITY
IRREGULARLY
IRREPARABLE
IRREPARABLY
IRREVERSIBLE
JEOPARDIZE
JEOPARDIZED
JUSTIFIABLE
KICKBACK
KICKBACKS
KNOWINGLY
LACK
LACKED
LACKING
LACKLUSTER
LACKS
LAG
LAGGED
LAGGING
LAGS
LAPSE
LAPSED
LAPSES
LAPSING
LATE
LAUNDERING
LAYOFF
LAYOFFS
LIE
LIMITATION
LIMITATIONS
LINGERING
LIQUIDATE
LIQUIDATED
LIQUIDATES
LIQUIDATING
LIQUIDATION
LIQUIDATIONS
LIQUIDATOR
LIQUIDATORS
LITIGANT
LITIGANTS
LITIGATE
LITIGATED
LITIGATES
LITIGATING
LITIGATION
LITIGATIONS
LOCKOUT
LOCKOUTS
LOSE
LOSES
LOSING
LOSS
LOSSES
LOST
LYING
MALFEASANCE
MALFUNCTION
MALFUNCTIONED
MALFUNCTIONING
MALFUNCTIONS
MALICE
MALICIOUS
MALICIOUSLY
MALPRACTICE
MANIPULATE
MANIPULATED
MANIPULATES
MANIPULATING
MANIPULATION
MANIPULATIONS
MANIPULATIVE
MARKDOWN
MARKDOWNS
MISAPPLICATION
MISAPPLICATIONS
MISAPPLIED
MISAPPLIES
MISAPPLY
MISAPPLYING
MISAPPROPRIATE
MISAPPROPRIATED
MISAPPROPRIATES
MISAPPROPRIATING
MISAPPROPRIATION
MISAPPROPRIATIONS
MISBRANDED
MISCALCULATE
MISCALCULATED
MISCALCULATES
MISCALCULATING
MISCALCULATION
MISCALCULATIONS
MISCHARACTERIZATION
MISCHIEF
MISCLASSIFICATION
MISCLASSIFICATIONS
MISCLASSIFIED
MISCLASSIFY
MISCOMMUNICATION
MISCONDUCT
MISDATED
MISDEMEANOR
MISDEMEANORS
MISDIRECTED
MISHANDLE
MISHANDLED
MISHANDLES
MISHANDLING
MISINFORM
MISINFORMATION
MISINFORMED
MISINFORMING
MISINFORMS
MISINTERPRET
MISINTERPRETATION
MISINTERPRETATIONS
MISINTERPRETED
MISINTERPRETING
MISINTERPRETS
MISJUDGE
MISJUDGED
MISJUDGES
MISJUDGING
MISJUDGMENT
MISJUDGMENTS
MISLABEL
MISLABELED
MISLABELING
MISLABELLED
MISLABELS
MISLEAD
MISLEADING
MISLEADINGLY
MISLEADS
MISLED
MISMANAGE
MISMANAGED
MISMANAGEMENT
MISMANAGES
MISMANAGING
MISMATCH
MISMATCHED
MISMATCHES
MISMATCHING
MISPLACED
MISPRICE
MISPRICING
MISPRICINGS
MISREPRESENT
MISREPRESENTATION
MISREPRESENTATIONS
MISREPRESENTED
MISREPRESENTING
MISREPRESENTS
MISS
MISSED
MISSES
MISSTATE
MISSTATED
MISSTATEMENT
MISSTATEMENTS
MISSTATES
MISSTATING
MISSTEP
MISSTEPS
MISTAKE
MISTAKEN
MISTAKENLY
MISTAKES
MISTAKING
MISTRIAL
MISTRIALS
MISUNDERSTAND
MISUNDERSTANDING
MISUNDERSTANDINGS
MISUNDERSTOOD
MISUSE
MISUSED
MISUSES
MISUSING
MONOPOLISTIC
MONOPOLISTS
MONOPOLIZATION
MONOPOLIZE
MONOPOLIZED
MONOPOLIZES
MONOPOLIZING
MONOPOLY
MORATORIA
MORATORIUM
MORATORIUMS
MOTHBALLED
MOTHBALLING
NEGATIVE
NEGATIVELY
NEGATIVES
NEGLECT
NEGLECTED
NEGLECTFUL
NEGLECTING
NEGLECTS
NEGLIGENCE
NEGLIGENCES
NEGLIGENT
NEGLIGENTLY
NONATTAINMENT
NONCOMPETITIVE
NONCOMPLIANCE
NONCOMPLIANCES
NONCOMPLIANT
NONCOMPLYING
NONCONFORMING
NONCONFORMITIES
NONCONFORMITY
NONDISCLOSURE
NONFUNCTIONAL
NONPAYMENT
NONPAYMENTS
NONPERFORMANCE
NONPERFORMANCES
NONPERFORMING
NONPRODUCING
NONPRODUCTIVE
NONRECOVERABLE
NONRENEWAL
NUISANCE
NUISANCES
NULLIFICATION
NULLIFICATIONS
NULLIFIED
NULLIFIES
NULLIFY
NULLIFYING
OBJECTED
OBJECTING
OBJECTION
OBJECTIONABLE
OBJECTIONABLY
OBJECTIONS
OBSCENE
OBSCENITY
OBSOLESCENCE
OBSOLETE
OBSTACLE
OBSTACLES
OBSTRUCT
OBSTRUCTED
OBSTRUCTING
OBSTRUCTION
OBSTRUCTIONS
OFFENCE
OFFENCES
OFFEND
OFFENDED
OFFENDER
OFFENDERS
OFFENDING
OFFENDS
OMISSION
OMISSIONS
OMIT
OMITS
OMITTED
OMITTING
ONEROUS
OPPORTUNISTIC
OPPORTUNISTICALLY
OPPOSE
OPPOSED
OPPOSES
OPPOSING
OPPOSITION
OPPOSITIONS
OUTAGE
OUTAGES
OUTDATED
OUTMODED
OVERAGE
OVERAGES
OVERBUILD
OVERBUILDING
OVERBUILDS
OVERBUILT
OVERBURDEN
OVERBURDENED
OVERBURDENING
OVERCAPACITIES
OVERCAPACITY
OVERCHARGE
OVERCHARGED
OVERCHARGES
OVERCHARGING
OVERCOME
OVERCOMES
OVERCOMING
OVERDUE
OVERESTIMATE
OVERESTIMATED
OVERESTIMATES
OVERESTIMATING
OVERESTIMATION
OVERESTIMATIONS
OVERLOAD
OVERLOADED
OVERLOADING
OVERLOADS
OVERLOOK
OVERLOOKED
OVERLOOKING
OVERLOOKS
OVERPAID
OVERPAYMENT
OVERPAYMENTS
OVERPRODUCED
OVERPRODUCES
OVERPRODUCING
OVERPRODUCTION
OVERRUN
OVERRUNNING
OVERRUNS
OVERSHADOW
OVERSHADOWED
OVERSHADOWING
OVERSHADOWS
OVERSTATE
OVERSTATED
OVERSTATEMENT
OVERSTATEMENTS
OVERSTATES
OVERSTATING
OVERSUPPLIED
OVERSUPPLIES
OVERSUPPLY
OVERSUPPLYING
OVERTLY
OVERTURN
OVERTURNED
OVERTURNING
OVERTURNS
OVERVALUE
OVERVALUED
OVERVALUING
PANIC
PANICS
PENALIZE
PENALIZED
PENALIZES
PENALIZING
PENALTIES
PENALTY
PERIL
PERILS
PERJURY
PERPETRATE
PERPETRATED
PERPETRATES
PERPETRATING
PERPETRATION
PERSIST
PERSISTED
PERSISTENCE
PERSISTENT
PERSISTENTLY
PERSISTING
PERSISTS
PERVASIVE
PERVASIVELY
PERVASIVENESS
PETTY
PICKET
PICKETED
PICKETING
PLAINTIFF
PLAINTIFFS
PLEA
PLEAD
PLEADED
PLEADING
PLEADINGS
PLEADS
PLEAS
PLED
POOR
POORLY
POSES
POSING
POSTPONE
POSTPONED
POSTPONEMENT
POSTPONEMENTS
POSTPONES
POSTPONING
PRECIPITATED
PRECIPITOUS
PRECIPITOUSLY
PRECLUDE
PRECLUDED
PRECLUDES
PRECLUDING
PREDATORY
PREJUDICE
PREJUDICED
PREJUDICES
PREJUDICIAL
PREJUDICING
PREMATURE
PREMATURELY
PRESSING
PRETRIAL
PREVENTING
PREVENTION
PREVENTS
PROBLEM
PROBLEMATIC
PROBLEMATICAL
PROBLEMS
PROLONG
PROLONGATION
PROLONGATIONS
PROLONGED
PROLONGING
PROLONGS
PRONE
PROSECUTE
PROSECUTED
PROSECUTES
PROSECUTING
PROSECUTION
PROSECUTIONS
PROTEST
PROTESTED
PROTESTER
PROTESTERS
PROTESTING
PROTESTOR
PROTESTORS
PROTESTS
PROTRACTED
PROTRACTION
PROVOKE
PROVOKED
PROVOKES
PROVOKING
PUNISHED
PUNISHES
PUNISHING
PUNISHMENT
PUNISHMENTS
PUNITIVE
PURPORT
PURPORTED
PURPORTEDLY
PURPORTING
PURPORTS
QUESTION
QUESTIONABLE
QUESTIONABLY
QUESTIONED
QUESTIONING
QUESTIONS
QUIT
QUITTING
RACKETEER
RACKETEERING
RATIONALIZATION
RATIONALIZATIONS
RATIONALIZE
RATIONALIZED
RATIONALIZES
RATIONALIZING
REASSESSMENT
REASSESSMENTS
REASSIGN
REASSIGNED
REASSIGNING
REASSIGNMENT
REASSIGNMENTS
REASSIGNS
RECALL
RECALLED
RECALLING
RECALLS
RECESSION
RECESSIONARY
RECESSIONS
RECKLESS
RECKLESSLY
RECKLESSNESS
REDACT
REDACTED
REDACTING
REDACTION
REDACTIONS
REDEFAULT
REDEFAULTED
REDEFAULTS
REDRESS
REDRESSED
REDRESSES
REDRESSING
REFUSAL
REFUSALS
REFUSE
REFUSED
REFUSES
REFUSING
REJECT
REJECTED
REJECTING
REJECTION
REJECTIONS
REJECTS
RELINQUISH
RELINQUISHED
RELINQUISHES
RELINQUISHING
RELINQUISHMENT
RELINQUISHMENTS
RELUCTANCE
RELUCTANT
RENEGOTIATE
RENEGOTIATED
RENEGOTIATES
RENEGOTIATING
RENEGOTIATION
RENEGOTIATIONS
RENOUNCE
RENOUNCED
RENOUNCEMENT
RENOUNCEMENTS
RENOUNCES
RENOUNCING
REPARATION
REPARATIONS
REPOSSESSED
REPOSSESSES
REPOSSESSING
REPOSSESSION
REPOSSESSIONS
REPUDIATE
REPUDIATED
REPUDIATES
REPUDIATING
REPUDIATION
REPUDIATIONS
RESIGN
RESIGNATION
RESIGNATIONS
RESIGNED
RESIGNING
RESIGNS
RESTATE
RESTATED
RESTATEMENT
RESTATEMENTS
RESTATES
RESTATING
RESTRUCTURE
RESTRUCTURED
RESTRUCTURES
RESTRUCTURING
RESTRUCTURINGS
RETALIATE
RETALIATED
RETALIATES
RETALIATING
RETALIATION
RETALIATIONS
RETALIATORY
RETRIBUTION
RETRIBUTIONS
REVOCATION
REVOCATIONS
REVOKE
REVOKED
REVOKES
REVOKING
RIDICULE
RIDICULED
RIDICULES
RIDICULING
RISKIER
RISKIEST
RISKY
SABOTAGE
SACRIFICE
SACRIFICED
SACRIFICES
SACRIFICIAL
SACRIFICING
SCANDALOUS
SCANDALS
SCRUTINIZE
SCRUTINIZED
SCRUTINIZES
SCRUTINIZING
SCRUTINY
SECRECY
SEIZE
SEIZED
SEIZES
SEIZING
SENTENCED
SENTENCING
SERIOUS
SERIOUSLY
SERIOUSNESS
SETBACK
SETBACKS
SEVER
SEVERE
SEVERED
SEVERELY
SEVERITIES
SEVERITY
SHARPLY
SHOCKED
SHORTAGE
SHORTAGES
SHORTFALL
SHORTFALLS
SHRINKAGE
SHRINKAGES
SHUT
SHUTDOWN
SHUTDOWNS
SHUTS
SHUTTING
SLANDER
SLANDERED
SLANDEROUS
SLANDERS
SLIPPAGE
SLIPPAGES
SLOW
SLOWDOWN
SLOWDOWNS
SLOWED
SLOWER
SLOWEST
SLOWING
SLOWLY
SLOWNESS
SLUGGISH
SLUGGISHLY
SLUGGISHNESS
SOLVENCIES
SOLVENCY
SPAM
SPAMMERS
SPAMMING
STAGGERING
STAGNANT
STAGNATE
STAGNATED
STAGNATES
STAGNATING
STAGNATION
STANDSTILL
STANDSTILLS
STOLEN
STOPPAGE
STOPPAGES
STOPPED
STOPPING
STOPS
STRAIN
STRAINED
STRAINING
STRAINS
STRESS
STRESSED
STRESSES
STRESSFUL
STRESSING
STRINGENT
SUBJECTED
SUBJECTING
SUBJECTION
SUBPOENA
SUBPOENAED
SUBPOENAS
SUBSTANDARD
SUE
SUED
SUES
SUFFER
SUFFERED
SUFFERING
SUFFERS
SUING
SUMMONED
SUMMONING
SUMMONS
SUMMONSES
SUSCEPTIBILITY
SUSCEPTIBLE
SUSPECT
SUSPECTED
SUSPECTS
SUSPEND
SUSPENDED
SUSPENDING
SUSPENDS
SUSPENSION
SUSPENSIONS
SUSPICION
SUSPICIONS
SUSPICIOUS
SUSPICIOUSLY
TAINT
TAINTED
TAINTING
TAINTS
TAMPERED
TENSE
TERMINATE
TERMINATED
TERMINATES
TERMINATING
TERMINATION
TERMINATIONS
TESTIFY
TESTIFYING
THREAT
THREATEN
THREATENED
THREATENING
THREATENS
THREATS
TIGHTENING
TOLERATE
TOLERATED
TOLERATES
TOLERATING
TOLERATION
TORTUOUS
TORTUOUSLY
TRAGEDIES
TRAGEDY
TRAGIC
TRAGICALLY
TRAUMATIC
TROUBLE
TROUBLED
TROUBLES
TURBULENCE
TURMOIL
UNABLE
UNACCEPTABLE
UNACCEPTABLY
UNACCOUNTED
UNANNOUNCED
UNANTICIPATED
UNAPPROVED
UNATTRACTIVE
UNAUTHORIZED
UNAVAILABILITY
UNAVAILABLE
UNAVOIDABLE
UNAVOIDABLY
UNAWARE
UNCOLLECTABLE
UNCOLLECTED
UNCOLLECTIBILITY
UNCOLLECTIBLE
UNCOLLECTIBLES
UNCOMPETITIVE
UNCOMPLETED
UNCONSCIONABLE
UNCONSCIONABLY
UNCONTROLLABLE
UNCONTROLLABLY
UNCONTROLLED
UNCORRECTED
UNCOVER
UNCOVERED
UNCOVERING
UNCOVERS
UNDELIVERABLE
UNDELIVERED
UNDERCAPITALIZED
UNDERCUT
UNDERCUTS
UNDERCUTTING
UNDERESTIMATE
UNDERESTIMATED
UNDERESTIMATES
UNDERESTIMATING
UNDERESTIMATION
UNDERFUNDED
UNDERINSURED
UNDERMINE
UNDERMINED
UNDERMINES
UNDERMINING
UNDERPAID
UNDERPAYMENT
UNDERPAYMENTS
UNDERPAYS
UNDERPERFORM
UNDERPERFORMANCE
UNDERPERFORMED
UNDERPERFORMING
UNDERPERFORMS
UNDERPRODUCED
UNDERPRODUCTION
UNDERREPORTING
UNDERSTATE
UNDERSTATED
UNDERSTATEMENT
UNDERSTATEMENTS
UNDERSTATES
UNDERSTATING
UNDERUTILIZATION
UNDERUTILIZED
UNDESIRABLE
UNDESIRED
UNDETECTED
UNDETERMINED
UNDISCLOSED
UNDOCUMENTED
UNDUE
UNDULY
UNECONOMIC
UNECONOMICAL
UNECONOMICALLY
UNEMPLOYED
UNEMPLOYMENT
UNETHICAL
UNETHICALLY
UNEXCUSED
UNEXPECTED
UNEXPECTEDLY
UNFAIR
UNFAIRLY
UNFAVORABILITY
UNFAVORABLE
UNFAVORABLY
UNFAVOURABLE
UNFEASIBLE
UNFIT
UNFITNESS
UNFORESEEABLE
UNFORESEEN
UNFORSEEN
UNFORTUNATE
UNFORTUNATELY
UNFOUNDED
UNFRIENDLY
UNFULFILLED
UNFUNDED
UNINSURED
UNINTENDED
UNINTENTIONAL
UNINTENTIONALLY
UNJUST
UNJUSTIFIABLE
UNJUSTIFIABLY
UNJUSTIFIED
UNJUSTLY
UNKNOWING
UNKNOWINGLY
UNLAWFUL
UNLAWFULLY
UNLICENSED
UNLIQUIDATED
UNMARKETABLE
UNMERCHANTABLE
UNMERITORIOUS
UNNECESSARILY
UNNECESSARY
UNNEEDED
UNOBTAINABLE
UNOCCUPIED
UNPAID
UNPERFORMED
UNPLANNED
UNPOPULAR
UNPREDICTABILITY
UNPREDICTABLE
UNPREDICTABLY
UNPREDICTED
UNPRODUCTIVE
UNPROFITABILITY
UNPROFITABLE
UNQUALIFIED
UNREALISTIC
UNREASONABLE
UNREASONABLENESS
UNREASONABLY
UNRECEPTIVE
UNRECOVERABLE
UNRECOVERED
UNREIMBURSED
UNRELIABLE
UNREMEDIED
UNREPORTED
UNRESOLVED
UNREST
UNSAFE
UNSALABLE
UNSALEABLE
UNSATISFACTORY
UNSATISFIED
UNSAVORY
UNSCHEDULED
UNSELLABLE
UNSOLD
UNSOUND
UNSTABILIZED
UNSTABLE
UNSUBSTANTIATED
UNSUCCESSFUL
UNSUCCESSFULLY
UNSUITABILITY
UNSUITABLE
UNSUITABLY
UNSUITED
UNSURE
UNSUSPECTED
UNSUSPECTING
UNSUSTAINABLE
UNTENABLE
UNTIMELY
UNTRUSTED
UNTRUTH
UNTRUTHFUL
UNTRUTHFULLY
UNTRUTHFULNESS
UNTRUTHS
UNUSABLE
UNWANTED
UNWARRANTED
UNWELCOME
UNWILLING
UNWILLINGNESS
UPSET
URGENCY
URGENT
USURIOUS
USURP
USURPED
USURPING
USURPS
USURY
VANDALISM
VERDICT
VERDICTS
VETOED
VICTIMS
VIOLATE
VIOLATED
VIOLATES
VIOLATING
VIOLATION
VIOLATIONS
VIOLATIVE
VIOLATOR
VIOLATORS
VIOLENCE
VIOLENT
VIOLENTLY
VITIATE
VITIATED
VITIATES
VITIATING
VITIATION
VOIDED
VOIDING
VOLATILE
VOLATILITY
VULNERABILITIES
VULNERABILITY
VULNERABLE
VULNERABLY
WARN
WARNED
WARNING
WARNINGS
WARNS
WASTED
WASTEFUL
WASTING
WEAK
WEAKEN
WEAKENED
WEAKENING
WEAKENS
WEAKER
WEAKEST
WEAKLY
WEAKNESS
WEAKNESSES
WILLFULLY
WORRIES
WORRY
WORRYING
WORSE
WORSEN
WORSENED
WORSENING
WORSENS
WORST
WORTHLESS
WRITEDOWN
WRITEDOWNS
WRITEOFF
WRITEOFFS
WRONG
WRONGDOING
WRONGDOINGS
WRONGFUL
WRONGFULLY
WRONGLY
"""

lmlist = lmneg.split("\n")
lmlist.extend(lmpos.split("\n"))
for term in lmlist:
    if minute.find(term) >= 0:
        print("-", term, "-")
